//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAllocation
    {
        public int ID { get; set; }
        public int ClassMasterID { get; set; }
        public int TeacherMasterID { get; set; }
        public int StudentMasterID { get; set; }
    
        public virtual ClassMaster ClassMaster { get; set; }
        public virtual StudentMaster StudentMaster { get; set; }
        public virtual TeacherMaster TeacherMaster { get; set; }
    }
}
